#!/bin/bash
systemSerial=$(dmidecode --string system-serial-number 2>/dev/null)
if [[ -z $systemSerial ]]; then
	systemSerial=$(cat /sys/class/dmi/id/product_serial)
fi
tagNum=$(uit-cli --serial "${systemSerial}" --key "client_lookup_by_serial" --value "${systemSerial}" --get | jq -r '.tagnumber' 2>/dev/null)
while [[ -z $tagNum ]]; do
	echo "Unable to find tag number for system serial ${systemSerial}"
	sleep 5
	tagNum=$(uit-cli --serial "${systemSerial}" --key "client_lookup_by_serial" --value "${systemSerial}" --get | jq -r '.tagnumber' 2>/dev/null)
done

while true; do
	fbgrab - > /tmp/screenshot.png
	printf '%s' "api_post|${tagNum}|live_image|/tmp/screenshot.png" | /opt/uit-toolbox/parse
	# Check if cancel job has been sent
	if [[ -n $(printf "%s" "api_get|job_name|tagnumber|${tagNum}" | /opt/uit-toolbox/parse) ]]; then
		sleep 2
	else
		sleep 10
	fi
done