#!/bin/bash
while true; do
	startingSystemUptime=$(cat /proc/uptime | awk '{print int($1)}')
	systemSerial=$(dmidecode --string system-serial-number 2>/dev/null)
	if [[ -z $systemSerial ]]; then
		systemSerial=$(cat /sys/class/dmi/id/product_serial)
	fi
	if [[ -z $systemSerial ]]; then
		sleep 5
		continue
	fi
	tagNum=$(printf "%s" "api_get|client_lookup|system_serial|${systemSerial}" | /opt/uit-toolbox/parse)
	if [[ -z $tagNum ]]; then
		sleep 5
		continue
	fi
	echo "api_post|${tagNum}|last_heard|$(date --iso-8601=seconds)" | /opt/uit-toolbox/parse

	for i in $(find /sys/class/hwmon/ -mindepth 1); do
		deviceName=$(cat ${i}/name)    
		if [[ $deviceName == "BAT0" || $deviceName == "BAT1" ]]; then
			if [[ -f ${i}/device/charge_full_design ]]; then
				battCapacityFactory=$(cat ${i}/device/charge_full_design)
			elif [[ -f ${i}/device/energy_full_design ]]; then 
				battCapacityFactory=$(cat ${i}/device/energy_full_design)
			fi
			battCharePcnt=$(cat ${i}/device/capacity)
			battStatus=$(cat ${i}/device/status)
			#battModel=$(cat ${i}/device/model_name)
			/sbin/uit-cli --tag "${tagNum}" --key battery_charge_pcnt --value "${battCharePcnt}"
		fi

		if [[ $deviceName == "nvme" ]]; then
			nvmeTemp=$(cat ${i}/temp1_input)
			nvmeMaxTemp=$(cat ${i}/temp1_max)
			nvmeAlarm=$(cat ${i}/temp1_alarm)
			nvmeFirmware=$(cat ${i}/device/firmware_rev)
			nvmeModel=$(cat ${i}/device/model)
			nvmeSerial=$(cat ${i}/device/serial)
			echo "job_queue|${tagNum}|disk_temp|${nvmeTemp}" | /opt/uit-toolbox/parse
			echo "job_queue|${tagNum}|max_disk_temp|${nvmeMaxTemp}" | /opt/uit-toolbox/parse
		fi

		# # Dell BIOS/Motherboard Temp
		# if [[ $deviceName == "dell_smm" ]]; then
		# 	tmpSum=0
		# 	tmpNum=0
		# 	for tmp in $(find ${i}/temp*_input); do
		# 		tmpSum=$(( tmpSum + tmp ))
		# 		tmpNum=$(( tmpNum + 1 ))
		# 	done
		# 	motherboardTemp=$(( tmpSum / tmpNum ))
		# fi
	done


	# See realtime energy usage
	if [[ -d /sys/class/powercap ]]; then
		uj1=0
		uj2=0

		for i in $(cat /sys/class/powercap/*/energy_uj 2>/dev/null); do
			uj1=$(( uj1 + i ))
		done
		sleep 1
		for i in $(cat /sys/class/powercap/*/energy_uj 2>/dev/null); do
			uj2=$(( uj2 + i ))
		done
		echo "job_queue|${tagNum}|watts_now|${uj1}|${uj2}" | /opt/uit-toolbox/parse
	fi


	# Check if running kernel is up to date
	for i in $(ls /lib/modules); do
		echo "${i}" | grep -i --quiet "$(uname -r)"
		if [[ ${PIPESTATUS[1]} == "0" ]]; then
			echo "job_queue|${tagNum}|kernel_updated|1" | /opt/uit-toolbox/parse
			break
		else
			echo "job_queue|${tagNum}|kernel_updated|" | /opt/uit-toolbox/parse
		fi
	done

	# Get memory info
	memTotal=$(cat /proc/meminfo  | grep -i memTotal | awk '{ print $2 }')
	memAvailable=$(cat /proc/meminfo  | grep -i memAvailable | awk '{ print $2 }')
	memUsage=$(( memTotal - memAvailable ))
	/sbin/uit-cli --tag "${tagNum}" --key memory_usage_kb --value "${memUsage}"

	# Get CPU temp and usage
	cpuUsage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d'%' -f1)
	avgTemp=0
	/sbin/uit-cli --tag "${tagNum}" --key cpu_current_usage --value "${cpuUsage}"
	for i in $(find /sys/class/hwmon/ -mindepth 1 -maxdepth 1); do
		hwmonName=$(cat ${i}/name)
		if [[ $hwmonName == "coretemp" || $hwmonName == "acpitz" ]]; then
			cpuTemps=( $(cat ${i}/temp*_input) )
			for temp in ${cpuTemps[@]}; do
				if [[ temp -gt 0 ]]; then
					avgTemp=$(( avgTemp + temp ))
				fi
			done
			avgTemp=$(( avgTemp / ${#cpuTemps[@]} ))
		fi
	done
	/sbin/uit-cli --tag "${tagNum}" --key cpu_millidegrees_c --value "${avgTemp}"

	# CPU frequency
	cpuMHzArr=( $(cat /proc/cpuinfo | grep 'cpu MHz' | awk '{ print $4 }') )
	cpuMhzSum=0
	for i in ${cpuMHzArr[@]}; do 
		cpuMhzSum=$(echo "$cpuMhzSum + $i" | bc);
	done
	cpuMhzAvg=$(echo "scale=2; $cpuMhzSum / ${#cpuMHzArr[@]}" | bc)
	/sbin/uit-cli --tag "${tagNum}" --key cpu_current_mhz --value "${cpuMhzAvg}"

	# Get network link speed
	for i in $(ip addr | awk '/state UP/ {print $2}' | sed 's/://g'); do
		linkSpeed=$(cat /sys/class/net/${i}/speed 2>/dev/null)
		originalTxBytes=$(cat /sys/class/net/${i}/statistics/tx_bytes)
		originalRxBytes=$(cat /sys/class/net/${i}/statistics/rx_bytes)
		originalBytes=$(( originalTxBytes + originalRxBytes ))
		sleep 1
		newTxBytes=$(cat /sys/class/net/${i}/statistics/tx_bytes)
		newRxBytes=$(cat /sys/class/net/${i}/statistics/rx_bytes)
		newBytes=$(( newTxBytes + newRxBytes ))
		netUsage=$(( (newBytes - originalBytes) * 8 ))
		echo "api_post|${tagNum}|network|${netUsage}|${linkSpeed}" | /opt/uit-toolbox/parse
	done

	# Check if cancel job has been sent
	if [[ $(echo "SELECT job_name AS result FROM job_queue WHERE tagnumber = '${tagNum}'" | /opt/uit-toolbox/select) == "cancel" ]]; then
		echo "job_queue|${tagNum}|job_name|" | /opt/uit-toolbox/parse
		echo "job_queue|${tagNum}|job_queued|FALSE" | /opt/uit-toolbox/parse
		printf "%s" "api_post|${tagNum}|job_queued_at|clear|${UUID}" | /opt/uit-toolbox/parse
		echo "job_queue|${tagNum}|job_active|FALSE" | /opt/uit-toolbox/parse
		echo "job_queue|${tagNum}|status|fail - Job cancelled :(" | /opt/uit-toolbox/parse
		UUID=$(printf '%s' "SELECT uuid AS result FROM jobstats WHERE tagnumber = '${tagNum}' AND host_connected = TRUE ORDER BY time DESC LIMIT 1" | /opt/uit-toolbox/select)
		echo "general|erase_completed||${UUID}" | /opt/uit-toolbox/parse
		echo "general|clone_completed||${UUID}" | /opt/uit-toolbox/parse
		echo "general|job_cancelled|TRUE|${UUID}" | /opt/uit-toolbox/parse
		pkill --terminal tty1
	fi


	#Network link speed
	for i in $(ip addr | awk '/state UP/ {print $2}' | sed 's/://g'); do
		netSpeed=$(cat /sys/class/net/${i}/speed 2>/dev/null)
		if [[ $netSpeed != $(echo "SELECT network_speed AS result FROM job_queue WHERE tagnumber = '${tagNum}'" | /opt/uit-toolbox/select) ]]; then
			echo "job_queue|${tagNum}|network_speed|$netSpeed" | /opt/uit-toolbox/parse
		fi
	done

	# Sleep before next loop
	sleep 1
	
	endingSystemUptime=$(cat /proc/uptime | awk '{print int($1)}')

	timeToLoop=$((endingSystemUptime - startingSystemUptime))
	if [[ -z $timeToLoop ]]; then
		timeToLoop=0
	fi
	clientAppUptime=$((clientAppUptime + timeToLoop))
	echo "${clientAppUptime}" > /root/client_app_uptime

	/sbin/uit-cli --tag "${tagNum}" --key client_app_uptime --value "${clientAppUptime}"
	/sbin/uit-cli --tag "${tagNum}" --key system_uptime --value "${endingSystemUptime}"
done