Set-Variable -name "systemSerial" -Value ((Get-WmiObject -Class Win32_ComputerSystemProduct | Select-Object -ExpandProperty IdentifyingNumber).trim())
if ($systemSerial -eq "") {
	Set-Variable -name "systemSerial" -Value ((Get-WmiObject -Class Win32_SystemEnclosure | Select-Object -ExpandProperty SerialNumber).trim())
}
Set-Variable -name "chassisType" -Value ((Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty ChassisSKUNumber).trim())
Set-Variable -name "adDomain" -Value ((Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Domain).trim())
Set-Variable -name "adDomainJoined" -Value (($null -ne $adDomain) -and ($adDomain -ne ""))
Set-Variable -name "systemManufacturer" -Value ((Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Manufacturer).trim())
Set-Variable -name "systemModel" -Value ((Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Model).trim())
Set-Variable -name "biosVersion" -Value ((Get-WmiObject -Class Win32_BIOS | Select-Object -ExpandProperty SMBIOSBIOSVersion).trim())
Set-Variable -name "osVersion" -Value ((Get-WmiObject -Class Win32_OperatingSystem | Select-Object -ExpandProperty Version).trim())
Set-Variable -name "memorySizeBytes" -Value ((Get-WmiObject -Class Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum)
Set-Variable -name "osName" -Value ((Get-WmiObject -Class Win32_OperatingSystem | Select-Object -ExpandProperty Caption).trim())
Set-Variable -name "osInstalledAt" -Value ((Get-WmiObject -Class Win32_OperatingSystem | Select-Object -ExpandProperty InstallDate).trim())
Set-Variable -name "memorySpeedMHz" -Value ((Get-WmiObject -Class Win32_PhysicalMemory | Select-Object -ExpandProperty Speed | Select-Object -First 1))
Set-Variable -name "cpuModel" -Value ((Get-WmiObject -Class Win32_Processor | Select-Object -ExpandProperty Name).trim())
Set-Variable -name "cpuCores" -Value ((Get-WmiObject -Class Win32_Processor | Select-Object -ExpandProperty NumberOfCores))
Set-Variable -name "cpuThreads" -Value ((Get-WmiObject -Class Win32_Processor | Select-Object -ExpandProperty NumberOfLogicalProcessors))
Set-Variable -name "diskSizeBytes" -Value ((Get-WmiObject -Class Win32_DiskDrive | Measure-Object -Property Size -Sum).Sum)
Set-Variable -name "ethernetMacAddr" -Value ((Get-WmiObject -Class Win32_NetworkAdapterConfiguration | Where-Object { $_.IPEnabled } | Select-Object -ExpandProperty MACAddress | Select-Object -First 1).trim())
Set-Variable -name "wifiMacAddr" -Value (Get-WmiObject -Class Win32_NetworkAdapterConfiguration | Where-Object { $_.IPEnabled -and $_.Description -match "Wireless" } | Select-Object -ExpandProperty MACAddress | Select-Object -First 1 | ForEach-Object { $_.Trim() })
Set-Variable -name "diskModel" -Value ((Get-WmiObject -Class Win32_DiskDrive | Select-Object -ExpandProperty Model | Select-Object -First 1).trim())
Set-Variable -name "cpuTemp" -Value ((Get-WmiObject -Namespace root\wmi -Class MSAcpi_ThermalZoneTemperature | Select-Object -ExpandProperty CurrentTemperature | Select-Object -First 1) / 10 - 273.15)
Set-Variable -name "batteryChargePercent" -Value (Get-WmiObject -Class Win32_Battery | Select-Object -ExpandProperty EstimatedChargeRemaining)