#!/usr/bin/php
<?php
include('/opt/uit-toolbox/include.php');


$fd = fopen('php://stdin', 'r');
$input = trim(fgets(STDIN));
fclose($fd);

$arr = explode('|', $input);

$dbPSQL = new dbPSQL();


if ($arr[0] == "init") {
	$uuid = $arr[1];
	$tagNum = $arr[2];
	$serial = $arr[3];
	$macAddr = $arr[4];
	$wifiMac = $arr[5];
	$tpmVersion = $arr[6];

	$dbPSQL->insertJob($uuid);

	$dbPSQL->updateJob("tagnumber", $tagNum, $uuid);
	$dbPSQL->updateJob("system_serial", $serial, $uuid);
	$dbPSQL->updateJob("etheraddress", $macAddr, $uuid);
	if (strFilter($macAddr) === 0) {
		$dbPSQL->updateSystemData($tagNum, "etheraddress", $macAddr);
	}
	if (strFilter($wifiMac) === 0) {
		$dbPSQL->updateSystemData($tagNum, "wifi_mac", $wifiMac);
	}
	if (strFilter($tpmVersion) === 0) {
		$dbPSQL->updateClientHealth($tagNum, "tpm_version", $tpmVersion);
	}
	$dbPSQL->updateJob("date", $date, $uuid);

	function queryTime($queryTime) {
		$dbPSQL = new dbPSQL();
		$time = updateTimeValue();
		$dbPSQL->Pselect("SELECT COUNT(time) AS count FROM jobstats WHERE time = :time", array(':time' => $queryTime));
		foreach ($dbPSQL->get() as $key => $value) {
			return $value["count"];
		}
	}

	do {
		sleep(1);
		$time = updateTimeValue();
	} while (queryTime($time) > 0);

	$dbPSQL->updateJob("time", $time, $uuid);
}

if ($arr[0] == "location") {

	if (empty($arr[7])) {
		$arr[7] = "unknown";
	}

	if ($arr[1] == "begin") {
		$tagNum = $arr[2];
		$serial = $arr[3];
		$location = $arr[4];
		$status = "0";
		$note = "";
	}

	if ($arr[1] == "end") {
		$tagNum = $arr[2];
		$serial = $arr[3];
		$location = $arr[4];
		$status = "0";
		$note = "";
	}

	if ($arr[1] == "custom") {
		$tagNum = $arr[2];
		$serial = $arr[3];
		$location = $arr[4];
		$status = $arr[5];
		$note = $arr[6];
	}

	//$uuid = uniqid("location-", true);

	//$dbPSQL->insertJob($uuid);
	//$dbPSQL->updateJob("tagnumber", $tagNum, $uuid);
	//$dbPSQL->updateJob("system_serial", $serial, $uuid);
	//$dbPSQL->updateJob ("date", $date, $uuid);
	//$dbPSQL->updateJob ("time", $time, $uuid);

	$dbPSQL->insertLocation($time, $tagNum);
	$dbPSQL->updateLocation("system_serial", $serial, $time);
	$dbPSQL->updateLocation("location", $location, $time);
	$dbPSQL->updateLocation("status", boolval($status), $time);
	$dbPSQL->updateLocation("note", $note, $time);
}


if ($arr[0] == "general") {
	$key = $arr[1];
	$value = $arr[2];
	$uuid = $arr[3];
	

	if ($key == "avg_cpu_temp") {
		$value = round(bcdiv($value, 1000, 2), 0);
	}

	if (!empty($arr[4]) && $arr[4] == "nvme") {
		$value = bcmul($value, 512, 4);
		$value = bcdiv($value, 1000000000, 2);
	} elseif (!empty($arr[4]) && $arr[4] == "sata") {
		if (!empty($arr[5]) && $arr[5] == "gib") {
			$value = bcdiv($value, 1024, 2);
		} else {
			$value = bcmul($value, 512, 4);
			$value = bcdiv($value, 1000000000000, 2);
		}
	}

	if ($key == "disk_type") {
		if ($value == "1") {
			$value = "hdd";
		} elseif ($value == "0") {
			$value = "ssd";
		} elseif ($value == "nvme") {
			$value = "nvme";
		} else {
			$value = "NULL";
		}
	}

	if ($key == "ram_capacity") {
		$value = round($value / 1000000, 0);
	}

	if ($key === "battery_health") {
		$value = round($value, 0);
		$ch = curl_init();
		$encodedUUID=curl_escape($ch, $uuid);
		$url = "https://UIT_WEB_HTTPS_HOST:UIT_WEB_HTTPS_PORT/api/client/health/battery?uuid=" . $encodedUUID;
		$body = json_encode(['battery_health' => $value]);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
		curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			'Content-Type: application/json',
			'Content-Length: ' . strlen($body),
			'User-Agent: uit-client'
		));
		$response = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error updating battery_health: ' . curl_error($ch);
		}
		return;
	}

	if ((is_bool($value) === true && boolval($value) === true) || $value == "TRUE") {
		$dbPSQL->updateJob($key, true, $uuid);
	} else if ((is_bool($value) === true && boolval($value) === false) || $value == "FALSE") {
		$dbPSQL->updateJob($key, false, $uuid);
	} else {
		$dbPSQL->updateJob($key, $value, $uuid);
	}
}

if ($arr[0] == "hardware_data") {
	$tagNum = $arr[1];
	$key = $arr[2];
	$value = $arr[3];

	$dbPSQL->Pselect("SELECT tagnumber FROM hardware_data WHERE tagnumber = :tagnumber", array(':tagnumber' => $tagNum));
	if (is_array($dbPSQL->get()) === FALSE) {
		$dbPSQL->insertSystemData($tagNum);
	}

	if ((is_bool($value) === true && boolval($value) === true) || $value == "TRUE") {
		$dbPSQL->updateSystemData($tagNum, $key, true);
	} else if ((is_bool($value) === true && boolval($value) === false) || $value == "FALSE") {
		$dbPSQL->updateSystemData($tagNum, $key, false);
	} else {
		$dbPSQL->updateSystemData($tagNum, $key, $value);
	}
}

if ($arr[0] == "system-stats") {
	$uuid = $arr[2];
	if ($arr[1] == "cpu") {
		$cpuSum = null;
		$cpuLineCount = null;
		$lines = file('/tmp/cpu-usage.txt');
		foreach ($lines as $lineNum => $line) {
			$cpuSum = $cpuSum + $line;
			$cpuLineCount = $cpuLineCount + 1;
		}
		$cpuAvg = $cpuSum / $cpuLineCount;
		$dbPSQL->updateJob("avg_cpu_usage", $cpuAvg, $uuid);
	} elseif ($arr[1] == "network") {
		$netSum = null;
		$netLineCount = null;
		$lines = file('/tmp/network-usage.txt');
		foreach ($lines as $lineNum => $line) {
			$netSum = $netSum + $line;
			$netLineCount = $netLineCount + 1;
		}
		$netSum = $netSum / 1048576 * 8;
		if ($netLineCount > 0) {
			$netAvg = $netSum / $netLineCount;
		} else {
			$netAvg = 0;
		}
		$dbPSQL->updateJob("avg_network_usage", $netAvg, $uuid);
	}
}

if ($arr[0] == "job_queue") {
	$tagNum = $arr[1];
	$key = $arr[2];
	$value = $arr[3];

	if ($key == "job_queued") {
		if ($value == "0") {
			$value = "NULL";
		} elseif ($value == "1") {
			$value = "data collection";
		} elseif ($value == "2") {
			$value = "hpEraseAndClone";
		} elseif ($value == "3") {
			$value = "nvmeErase";
		} elseif ($value == "9") {
			$value = "update";
		} elseif ($value == "8") {
			$value = "findmy";
		}
	}

	if ($key == "disk_temp" || $key == "max_disk_temp") {
		if ($value > 1000) {
			$cur = round(bcdiv($value, 1000, 2), 0);
			$value = $cur;
		}
	}

	if ($key == "watts_now") {
	$first = $value;
	$firstWatts = $first / 1e6;
	$second = $arr[4];
	$secWatts = $second / 1e6;

	$value = round(($secWatts - $firstWatts), 0);
	}

	if ($value == "TRUE") {
		$dbPSQL->updateJobQueue($tagNum, $key, true);
	} else if ($value == "FALSE") {
		$dbPSQL->updateJobQueue($tagNum, $key, false);
	} else {
		$dbPSQL->updateJobQueue($tagNum, $key, $value);
	}
}

if ($arr[0] == "client_health") {
	$tagNum = $arr[1];
	$key = $arr[2];
	$value = $arr[3];

	$dbPSQL->updateClientHealth($tagNum, $key, $value);
}

if ($arr[0] == "live_images") {
	$tagNum = $arr[1];
	$key = $arr[2];
	$fileName = $arr[3];

	$dbPSQL->Pselect("SELECT tagnumber FROM live_images WHERE tagnumber = :tagnumber", array(':tagnumber' => $tagNum));
	if (strFilter($dbPSQL->get()) === 1) {
		$dbPSQL->insertLiveImages($tagNum);
	}

	if ($arr[2] == "screenshot") {
		$fd = fopen($fileName, 'r');
		$rawImageData = fread($fd, filesize($fileName));
		$imageObject = imagecreatefromstring($rawImageData);
		imageinterlace($imageObject, true);
		fclose($fd);
		if ($imageObject !== false) {
			ob_start();
			imagejpeg($imageObject, NULL, 100);
			$imageBuffer = ob_get_clean();
			$imageFileConverted = base64_encode($imageBuffer);
			$value = $imageFileConverted;
			unset($imageBuffer);
			imagedestroy($imageObject);
		}
	}

	$dbPSQL->updateLiveImages($tagNum, "screenshot", $imageFileConverted);
	$dbPSQL->updateLiveImages($tagNum, "time", $time);
}

if ($arr[0] === "api") {
	$tagNum = (int)$arr[1];
	$key = $arr[2];
	$value = $arr[3];
	if (!empty($arr[4])) {
		$value2 = $arr[4];
	}

	$baseURL = "https://UIT_WEB_HTTPS_HOST:UIT_WEB_HTTPS_PORT";
	$ch = curl_init();
	$encodedTag=curl_escape($ch, $tagNum);
	$encodedKey=curl_escape($ch, $key);
	$encodedValue=curl_escape($ch, $value);

	if ($key === "memory") {
		// api|${tagNum}|memory|${memAvailable}|${memTotal}
		$url = "/api/client/memory";
		$body = json_encode([
			'tagnumber' => $tagNum,
			'memory_usage' => (int)$value,
			'memory_capacity' => (int)$value2
		]);
	}
	if ($key === "cpu_usage") {
		$usage = floatval($value);
		$url = "/api/client/cpu/usage";
		$body = json_encode([
			'tagnumber' => $tagNum,
			'cpu_usage' => floatval($value),
		]);
	}
	if ($key === "cpu_temp") {
		$usage = floatval($value);
		$url = "/api/client/cpu/temp";
		$body = json_encode([
			'tagnumber' => $tagNum,
			'cpu_millidegrees_c' => (int)$value,
		]);
	}
	if ($key === "network") {
		$url = "/api/client/network/usage";
		$body = json_encode([
			'tagnumber' => $tagNum,
			'network_usage' => (int)$value,
			'link_speed' => (int)$value2
		]);
	}

	if ($key === "uptime") {
		$url = "/api/client/uptime";
		$body = json_encode([
			'tagnumber' => $tagNum,
			'client_app_uptime' => (int)$value,
			'system_uptime' => (int)$value2,
		]);
	}

	if ($key === "last_hardware_check") {
		$url = "/api/client/health/last_hardware_check";
		$dt = new DateTime("now", new DateTimeZone("UTC"));
		$body = json_encode([
			'tagnumber' => $tagNum,
			'last_hardware_check' => $dt->format(DATE_RFC3339_EXTENDED)
		]);
	}

	if ($key === "system_serial") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'system_serial' => $value
		]);
	}

	if ($key === "system_manufacturer") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'system_manufacturer' => $value
		]);
	}

	if ($key === "system_model") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'system_model' => $value
		]);
	}

	if ($key === "system_uuid") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'system_uuid' => $value
		]);
	}

	if ($key === "system_sku") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'system_sku' => $value
		]);
	}

	if ($key === "chassis_type") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'chassis_type' => $value
		]);
	}

	if ($key === "cpu_manufacturer") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'cpu_manufacturer' => $value
		]);
	}

	if ($key === "cpu_model") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'cpu_model' => $value
		]);
	}

	if ($key === "cpu_max_speed_mhz") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'cpu_max_speed_mhz' => $value
		]);
	}

	if ($key === "cpu_core_count") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'cpu_core_count' => $value
		]);
	}

	if ($key === "cpu_thread_count") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'cpu_thread_count' => $value
		]);
	}

	if ($key === "motherboard_manufacturer") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'motherboard_manufacturer' => $value
		]);
	}

	if ($key === "motherboard_serial") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			'motherboard_serial' => $value
		]);
	}

	if ($key === "disk_reads") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_reads` => $value
		]);
	}

	if ($key === "disk_writes") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_writes` => $value
		]);
	}

	if ($key === "disk_model") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_model` => $value
		]);
	}

	if ($key === "disk_serial") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_serial` => $value
		]);
	}

	if ($key === "disk_size") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_size` => $value
		]);
	}

	if ($key === "disk_firmware") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_firmware` => $value
		]);
	}

	if ($key === "disk_type") {
		$url = "/api/client/hardware";
		if ($key === "disk_type") {
			if ($value == "1") {
				$value = "hdd";
			} elseif ($value == "0") {
				$value = "ssd";
			} elseif ($value == "nvme") {
				$value = "nvme";
			} else {
				$value = "";
			}
		}
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_type` => $value
		]);
	}

	if ($key === "disk_power_on_hours") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_power_on_hours` => $value
		]);
	}

	if ($key === "disk_power_cycles") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_power_cycles` => $value
		]);
	}

	if ($key === "disk_errors") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`disk_errors` => $value
		]);
	}

	if ($key === "bios_version") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`bios_version` => $value
		]);
	}

	if ($key === "bios_release_date") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`bios_release_date` => $value
		]);
	}

	if ($key === "bios_firmware") {
		$url = "/api/client/hardware";
		$body = json_encode([
			'transaction_uuid' => $value2,
			'tagnumber' => $tagNum,
			`bios_firmware` => $value
		]);
	}
	

	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
	curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
	curl_setopt($ch, CURLOPT_URL, $baseURL . $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, array(
		'Content-Type: application/json',
		'Content-Length: ' . strlen($body),
		'User-Agent: uit-client'
	));
	$response = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error updating battery_health: ' . curl_error($ch);
	}
	return;

}

?>