#!/bin/bash

curl --silent --show-error 'http://10.0.0.1:8080/client/certs/uit-web.crt' --output /usr/local/share/ca-certificates/uit-web.crt
while [ ! -f /usr/local/share/ca-certificates/uit-web.crt ]; do
  echo "Failed to download web cert, trying again..."
  curl --silent --show-error 'http://10.0.0.1:8080/client/certs/uit-web.crt' --output /usr/local/share/ca-certificates/uit-web.crt
  sleep 1
done
update-ca-certificates

jsonConfig=$(curl --silent --show-error 'https://10.0.0.1:31411/client/api/configs/uit-client?json=true')
while [ -z "$jsonConfig" ] || [[ "$jsonConfig" == *"error"* ]]; do
	echo "Failed to download client config (json), trying again..."
	jsonConfig=$(curl --silent --show-error 'https://10.0.0.1:31411/client/api/configs/uit-client?json=true')
	sleep 1
done

configKeys=$(printf "%s" "${jsonConfig}" | jq -r 'keys[]')

while IFS= read -r -d '' file; do
	if [[ $file == "/usr/sbin/uit-client" ]]; then
		continue
	fi
	if [[ -f $file ]]; then
		for key in ${configKeys}; do
			value=$(printf "%s" ${jsonConfig} | jq -r ''".${key}"'')
			value="${value//\\/\\\\}"
			value="${value//&/\\&}"
			value="${value//\//\\/}"
			value="${value//|/\\|}"
			sed -i "s|${key}|${value}|g" "$file"
		done
	fi
done < <(find /usr/sbin/ -type f -name 'uit-*' -print0; find /opt/uit-toolbox/include.php -type f -print0; find /opt/uit-toolbox/parse -type f -print0; find /opt/uit-toolbox/select -type f -print0)


curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-client' --output /tmp/uit-client
while [ ! -f /tmp/uit-client ]; do
  echo "Failed to download Go binary, trying again..."
  curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-client' --output /tmp/uit-client
  sleep 1
done
chmod 700 /tmp/uit-client
mv /tmp/uit-client /usr/sbin/uit-client

/usr/bin/chmod 700 /usr/sbin/uit-*
/usr/bin/chown root:root /usr/sbin/uit-*
/usr/bin/chmod 750 /opt/uit-toolbox/ -R
/usr/bin/chown root:root /opt/uit-toolbox/ -R