#!/bin/bash
printf '%s\n' "[Time]
NTP=10.0.0.1" > /etc/systemd/timesyncd.conf

systemctl daemon-reload &>/dev/null
/usr/bin/timedatectl set-timezone 'America/Chicago'
/usr/bin/timedatectl set-ntp true
/usr/bin/timedatectl set-local-rtc false

/usr/bin/chronyc add server 10.0.0.1 iburst
/usr/bin/chronyc makestep

curl --silent --show-error 'http://10.0.0.1:8080/client/certs/uit-web.crt' --output /usr/local/share/ca-certificates/uit-web.crt
while [ ! -f /usr/local/share/ca-certificates/uit-web.crt ]; do
  echo "Failed to download web cert, trying again..."
  curl --silent --show-error 'http://10.0.0.1:8080/client/certs/uit-web.crt' --output /usr/local/share/ca-certificates/uit-web.crt
  sleep 1
done
update-ca-certificates

jsonConfig=$(curl --silent --show-error 'https://10.0.0.1:31411/static/client/configs/uit-client?json=true')
while [ -z "$jsonConfig" ] || [[ "$jsonConfig" == *"error"* ]]; do
	echo "Failed to download client config (json), trying again..."
	jsonConfig=$(curl --silent --show-error 'https://10.0.0.1:31411/static/client/configs/uit-client?json=true')
	sleep 1
done

configKeys=$(printf "%s" "${jsonConfig}" | jq -r 'keys[]')

while IFS= read -r -d '' file; do
	if [[ $file == "/usr/sbin/uit-client" ]]; then
		continue
	fi
	if [[ -f $file ]]; then
		for key in ${configKeys}; do
			value=$(printf "%s" ${jsonConfig} | jq -r ''".${key}"'')
			value="${value//\\/\\\\}"
			value="${value//&/\\&}"
			value="${value//\//\\/}"
			value="${value//|/\\|}"
			sed -i "s|${key}|${value}|g" "$file"
		done
	fi
done < <(find /opt/uit-toolbox/windows/uit-toolbox-client.ps1 -type f -print0; find /usr/sbin/ -type f -name 'uit-*' -print0; find /opt/uit-toolbox/include.php -type f -print0; find /opt/uit-toolbox/parse -type f -print0; find /opt/uit-toolbox/select -type f -print0)


if [[ -f /tmp/uit-client ]]; then
	rm -f /tmp/uit-client
fi
if [[ -f /tmp/uit-clientd ]]; then
	rm -f /tmp/uit-clientd
fi
if [[ -f /tmp/uit-cli ]]; then
	rm -f /tmp/uit-cli
fi
curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-client' --output /tmp/uit-client
while [[ ! -f /tmp/uit-client ]]; do
  echo "Failed to download Go binary, trying again..."
  curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-client' --output /tmp/uit-client
  sleep 1
done
chmod 700 /tmp/uit-client
mv /tmp/uit-client /usr/sbin/uit-client

curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-clientd' --output /tmp/uit-clientd
while [[ ! -f /tmp/uit-clientd ]]; do
  echo "Failed to download Go binary, trying again..."
  curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-clientd' --output /tmp/uit-clientd
  sleep 1
done
chmod 700 /tmp/uit-clientd
mv /tmp/uit-clientd /usr/sbin/uit-clientd

curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-cli' --output /tmp/uit-cli
while [[ ! -f /tmp/uit-cli ]]; do
	echo "Failed to download Go binary, trying again..."
	curl --silent --show-error 'https://10.0.0.1:31411/client/pkg/uit-cli' --output /tmp/uit-cli
	sleep 1
done
chmod 700 /tmp/uit-cli
mv /tmp/uit-cli /usr/sbin/uit-cli

/usr/bin/chmod 700 /usr/sbin/uit-*
/usr/bin/chown root:root /usr/sbin/uit-*
/usr/bin/chmod 750 /opt/uit-toolbox/ -R
/usr/bin/chown root:root /opt/uit-toolbox/ -R

sudo systemctl daemon-reload
sudo systemctl enable --now uit-clientd.socket
sudo systemctl enable --now uit-clientd.service

systemctl restart uit-clientd.socket
systemctl restart uit-clientd.service